name: CI

on: 
 workflow_dispatch: 
 schedule:
   - cron: '30 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/develop' 

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch || 'develop' }}

    - name: Build and Test
      run: |
        echo "Running build and tests..."

    # - name: Send notification to Teams
    #   if: always()
    #   run: |
    #     curl -H 'Content-Type: application/json' -d '{
    #       "title": "Build Notification",
    #       "text": "The build for commit ${{ github.sha }} has been completed. Status: ${{ job.status }}."
    #     }' ${{ secrets.WEBHOOK }}
