name: CI

on: 
 push:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Test
      run: |
        echo "Running build and tests..."

    - name: Send notification to Teams
      if: always()
      run: |
        curl -H 'Content-Type: application/json' -d '{
          "title": "Build Notification",
          "text": "The build for commit ${{ github.sha }} has been completed. Status: ${{ job.status }}."
        }' ${{ secrets.TEAMS_WEBHOOK_URL }}
